# Generated by Django 2.1 on 2018-10-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('loc', models.CharField(max_length=20)),
                ('sal', models.IntegerField()),
            ],
            options={
                'db_table': 'empinfo',
                'ordering': ['-sal'],
            },
        ),
        migrations.AddIndex(
            model_name='emp',
            index=models.Index(fields=['name'], name='empinfo_name_797381_idx'),
        ),
    ]
